/*
 * Copyright (c) 2017 HAW Hamburg
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @ingroup     vslab-riot
 * @{
 *
 * @file
 * @brief       Sensor wrapper code
 *
 * @author      Sebastian Meiling <s@mlng.net>
 *
 * @}
 */

#include "log.h"
#ifdef MODULE_HDC1000
#include "hdc1000.h"
#include "hdc1000_params.h"
static hdc1000_t dev_hdc1000;
#else
#include "random.h"
#endif

#include "elect.h"

/**
 * @name Sensor value ranges for dummy device
 * @{
 * @note Values are scaled by factor 100
 */
#define ELECT_SENSOR_TEMP_MIN   (1800U)
#define ELECT_SENSOR_TEMP_MAX   (2800U)
#define ELECT_SENSOR_HUM_MIN    (3000U)
#define ELECT_SENSOR_HUM_MAX    (8000U)
/** @} */

/**
 * @brief Weight for average sensor values if dummy device is used
 *
 * For the dummy sensor device values are generated by a random function, to
 * avoid irratic value jumps a weighted average is calculated as follows:
 *
 * AVG = (((ELECT_SENSOR_ALPHA - 1) * VAL(n)) + VAL(n+1)) / ELECT_SENSOR_ALPHA
 */
#define ELECT_SENSOR_ALPHA      (4U)

static int16_t temp, hum;

int sensor_init(void)
{
    LOG_DEBUG("%s: begin\n", __func__);
#ifdef MODULE_HDC1000
    /* initialise humidity sensor hdc1000 */
    if (hdc1000_init(&dev_hdc1000, &hdc1000_params[0]) != HDC1000_OK) {
        LOG_ERROR("%s: init fail!\n", __func__);
        return 1;
    }
    hdc1000_read(&dev_hdc1000, &temp, &hum);
#else
    temp = (int16_t)random_uint32_range(ELECT_SENSOR_TEMP_MIN, ELECT_SENSOR_TEMP_MAX);
    hum  = (int16_t)random_uint32_range(ELECT_SENSOR_HUM_MIN, ELECT_SENSOR_HUM_MAX);
#endif /* MODULE_HDC1000 */
    LOG_DEBUG("%s: raw T: %"PRIi16", H: %"PRIi16"\n", __func__, temp, hum);
    LOG_DEBUG("%s: done\n", __func__);
    return 0;
}

int16_t sensor_read(void)
{
    LOG_DEBUG("%s: begin\n", __func__);
#ifdef MODULE_HDC1000
    hdc1000_read(&dev_hdc1000, &temp, &hum);
#else
    temp = (((ELECT_SENSOR_ALPHA - 1) * temp) +
            (int16_t)random_uint32_range(ELECT_SENSOR_TEMP_MIN, ELECT_SENSOR_TEMP_MAX)) / ELECT_SENSOR_ALPHA;
    hum  = (((ELECT_SENSOR_ALPHA - 1) * hum)  +
            (int16_t)random_uint32_range(ELECT_SENSOR_HUM_MIN, ELECT_SENSOR_HUM_MAX)) / ELECT_SENSOR_ALPHA;
#endif /* MODULE_HDC1000 */
    LOG_DEBUG("%s: raw T: %"PRIi16", H: %"PRIi16"\n", __func__, temp, hum);
    LOG_DEBUG("%s: done\n", __func__);
    return temp;
}
